In [1]:
# exercise 1
import numpy as np

base_pattern = np.array([[0,1],
                         [0,1]])

checkerboard_matrix = np.tile(base_pattern, (4, 4))

print(checkerboard_matrix)


[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [4]:
# exercise 2
array_2d = np.array([[2, 4, 6], [6, 8, 10]], np.int32)

print(array_2d.dtype)

int32


In [6]:
# exercise 3
array1 = np.random.random((5, 3))
print(f"Array 1 {array1}")
print()

array2 = np.random.random((3, 2))
print(f"Array 2 {array2}")
print()

mul_array = np.dot(array1, array2)

print(f"multiply array {mul_array}")


Array 1 [[0.48720708 0.54335209 0.73708739]
 [0.88674714 0.97979782 0.92982223]
 [0.0455669  0.68290883 0.70155322]
 [0.81538041 0.41995497 0.12145948]
 [0.92969212 0.23054972 0.78543004]]

Array 2 [[0.4810974  0.11138878]
 [0.41043124 0.3353631 ]
 [0.05441997 0.49045729]]

multiply array [[0.49751501 0.59799953]
 [0.87935228 0.88339981]
 [0.34038775 0.57817996]
 [0.57124986 0.29123232]
 [0.58464035 0.56609503]]


In [8]:
# exercise 4

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[(arr > 2) & (arr < 8)] *= -1
print(arr)

[ 1  2 -3 -4 -5 -6 -7  8  9]


In [9]:
# exercise 5
array_1 = np.array([1, 2, 3, 4])
array_2 = np.array([3, 4, 5, 6])

array_common = np.intersect1d(array_1, array_2)
print(array_common)

[3 4]


In [ ]:
# exercises 6
aa = np.seterr(all='ignore')
print(aa)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}


In [19]:
# exercise 7 
array_swap = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

array_swap[[0, 2]] = array_swap[[2, 0]]
print(array_swap)

[[ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]
 [10 11 12]]


In [27]:
# exercise 8
today_date = np.datetime64('today', 'D')
yesterday_date = today_date - np.timedelta64(1, 'D')
tomorrow_date = today_date + np.timedelta64(1, 'D')
print(f"Today date {today_date}")
print(f"Yesterday date {yesterday_date}")
print(f"Tomorrow date {tomorrow_date}")

Today date 2025-07-12
Yesterday date 2025-07-11
Tomorrow date 2025-07-13


In [38]:
# exercise 9
print("March, 2023")
print(np.arange('2023-08', '2023-09', dtype='datetime64[D]'))


March, 2023
['2023-08-01' '2023-08-02' '2023-08-03' '2023-08-04' '2023-08-05'
 '2023-08-06' '2023-08-07' '2023-08-08' '2023-08-09' '2023-08-10'
 '2023-08-11' '2023-08-12' '2023-08-13' '2023-08-14' '2023-08-15'
 '2023-08-16' '2023-08-17' '2023-08-18' '2023-08-19' '2023-08-20'
 '2023-08-21' '2023-08-22' '2023-08-23' '2023-08-24' '2023-08-25'
 '2023-08-26' '2023-08-27' '2023-08-28' '2023-08-29' '2023-08-30'
 '2023-08-31']


In [45]:
# exercise 10
array_decimal = np.array([1.5, 2.7, 3.4, 4.6, 5.9])

array_integer_int = array_decimal.astype(int)
print(array_integer_int)

array_integer_floor = np.floor(array_decimal)
print(array_integer_floor)

array_integer_truc = np.trunc(array_decimal)
print(array_integer_truc)

array_integer_ceil = np.ceil(array_decimal)
print(array_integer_ceil)


[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]
[2. 3. 4. 5. 6.]


In [ ]:
# Exercise 11
array_1D_scalar = np.array([1, 2, 3, 4, 5])
index_min_1D_scalar = np.argmin(array_1D_scalar)
print(f"index of minimum in 1D array : {index_min_1D_scalar}")

array_2D_scalar = np.array([[10, 20, 5], [30, 1, 40]])
index_min_2D_scalar = np.argmin(array_2D_scalar, axis=0)
print(index_min_2D_scalar)

index of minimum in 1D array : 0
[0 1 0]


In [5]:
# exercise 12
array_emu = np.array([[1, 2, 3], [4, 5, 6]])

for index , value in np.ndenumerate(array_emu):
    print(f"Index: {index}, Value: {value}")

Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (0, 2), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6


In [8]:
# exercise 13

array_input = np.array([10, 20, 30, 40, 50])
print("Orginal array")

np.put(array_input, [0,3], [100, 200])
print(f"New array {array_input}")

Orginal array
New array [100  20  30 200  50]


In [9]:
# exercise 14

array_near = np.array([10, 25, 35, 50, 80])
target = 40

nearest_index = np.argmin(np.abs(array_near - target))
nearest_value = array_near[nearest_index]

print(target)
print(nearest_value)

40
35


In [10]:
# exercise 15
array = np.array([
    [[[1, 5, 3, 2],
      [4, 2, 1, 7]],

     [[9, 0, 6, 4],
      [3, 8, 2, 5]]],

    [[[0, 3, 5, 1],
      [7, 2, 4, 6]],

     [[8, 1, 0, 9],
      [5, 3, 7, 2]]]
])

result = np.argmax(array, axis=-1)
print(result)

[[[1 3]
  [0 1]]

 [[2 0]
  [3 2]]]


In [ ]:
# exercise 16
import matplotlib.pyplot as plt