In [ ]:
# exercise 1 - Matrix manipulation 
import numpy as np

data = np.array(np.random.randint(1, 100, size = 25)).reshape(5, 5)
print(data)

print()

data[[2, 4]] = data[[4, 2]]
print(data)

[[97 33 43 45 60]
 [56 95 14 64  9]
 [11 12 10 91  6]
 [53 60 36 52 37]
 [73 74 10 56 39]]

[[97 33 43 45 60]
 [56 95 14 64  9]
 [73 74 10 56 39]
 [53 60 36 52 37]
 [11 12 10 91  6]]


In [8]:
# exercise 2 - Normalization
data_normalise = np.array([
    [4, 8, 6],
    [2, 10, 12]
])

data_min = np.min(data_normalise)
data_max = np.max(data_normalise)
normalise_data = (data_normalise - np.min(data_normalise)) / (np.max(data_normalise) - np.min(data_normalise))

print(normalise_data)

[[0.2 0.6 0.4]
 [0.  0.8 1. ]]


In [9]:
# exercise 3 - Z-score normalization
data_score = np.array([
    [4, 8, 6],
    [2, 10, 12]
])

z_score_data = (data_score - np.mean(data_score)) / np.std(data_score)
print(z_score_data)


[[-0.87831007  0.29277002 -0.29277002]
 [-1.46385011  0.87831007  1.46385011]]


In [10]:
# exercise 4 - Array splitting

data_splitting = np.array([
    [4, 8, 6],
    [2, 10, 12]
])

vector = np.ravel(data_splitting)
print(vector)

[ 4  8  6  2 10 12]


In [ ]:
# exercise 5 - Dot product
array_1 = np.array([1, 2, 3])
array_2 = np.array([3, 4, 5])

result = np.dot(array_1, array_2)
print(result)

26


In [17]:
# exercise 6 - Matrix multiplication
data1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

data2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

result_data1_data2 = np.dot(data1, data2)
print(result_data1_data2)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [8]:
# exercise 7 - Inverse of a matrix 
original_rev_array = np.array([
    [1, 2, 1],
    [0, 1, 0],
    [2, 3, 4]
])

print(f"Oringal array {original_rev_array}")

multi_array = np.multiply(original_rev_array, 2)
print(f"Multi array by 2 {multi_array}")

reverse_array = np.linalg.inv(original_rev_array)
print(f"Reverse of array \n {reverse_array}")

Oringal array [[1 2 1]
 [0 1 0]
 [2 3 4]]
Multi array by 2 [[2 4 2]
 [0 2 0]
 [4 6 8]]
Reverse of array 
 [[ 2.  -2.5 -0.5]
 [ 0.   1.   0. ]
 [-1.   0.5  0.5]]


In [9]:
# exercise 8 - Eigenvalues and eigenvectors
data_matrix = np.array([
    [4, 2, 1],
    [0, 3, -1],
    [0, 0, 2]
])

eigenvalues, eigenvectors = np.linalg.eig(data_matrix)

print("Eigenvalues: ")
print(eigenvalues)

print("\nEigenvectors (columns correspond to eigenvalues)")
print(eigenvectors)

Eigenvalues: 
[4. 3. 2.]

Eigenvectors (columns correspond to eigenvalues)
[[ 1.         -0.89442719 -0.72760688]
 [ 0.          0.4472136   0.48507125]
 [ 0.          0.          0.48507125]]


In [13]:
# exercise - Find missing values
array_mis = np.array([1.0 ,2.0, np.nan, 4.0])
print(array_mis)

is_nan_mask = np.isnan(array_mis)
print(is_nan_mask)

[ 1.  2. nan  4.]
[False False  True False]


In [14]:
# exercise 10 - Replace missing values
array_replace = np.array([1.0, 2.0, np.nan, 4.0, np.nan])

filled_array_replace = np.nan_to_num(array_replace, nan=0.0)
print(filled_array_replace)

[1. 2. 0. 4. 0.]
