In [8]:
import numpy as np
# 1 Create a 3x3x3 array with random values using np.random.random()
array_3d = np.random.random((3, 3, 3))
print(array_3d)
print(f"Min value int8 {array_3d.min}")
print(f"Min value int8 {array_3d.max}")

[[[0.00134439 0.69000903 0.18670312]
  [0.39071196 0.61184681 0.35538844]
  [0.45841861 0.33282843 0.46305657]]

 [[0.92949628 0.86730612 0.41075252]
  [0.50391982 0.8604149  0.66695073]
  [0.90924386 0.68123702 0.76743716]]

 [[0.94703418 0.77914438 0.83082733]
  [0.3287649  0.12968429 0.09051011]
  [0.27452644 0.09762638 0.79976743]]]
Min value int8 <built-in method min of numpy.ndarray object at 0x0000019B1967E430>
Min value int8 <built-in method max of numpy.ndarray object at 0x0000019B1967E430>


In [ ]:
# 3 Create a random vector of size 30 and find the mean* value.
array_30 = np.random.random(30)
array_30_mean = np.mean(array_30)
print(array_30)
print(array_30_mean)

[0.6463323  0.70168265 0.34309242 0.22894592 0.09627194 0.65953036
 0.63365826 0.56643201 0.21926639 0.92328904 0.367058   0.99809281
 0.89291127 0.97843915 0.94164267 0.71757926 0.34934609 0.72398919
 0.53298737 0.76329397 0.21196888 0.39464464 0.09771931 0.98199784
 0.87499013 0.06176129 0.16748285 0.35299123 0.78483846 0.40826508]
0.5540166923738056


In [11]:
# 4 Create a 2d array with 1 on the border and 0 inside (Hint: Use np.ones() and slicing).
array_x = np.ones((5, 5))

array_x[1:-1, 1:-1] = 0

print(array_x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
# Add a border (filled with 0’s) around an existing array using np.pad()
array = np.ones((3,3))

array_border_0 = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(array_border_0)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
# Replace all odd numbers in an array with -1 without changing the original array.
original = np.array([0, 1, 2, 3, 4, 5])

modified = original.copy()
modified[modified % 2 == 1] = -1

print(original)
print(modified)

[0 1 2 3 4 5]
[ 0 -1  2 -1  4 -1]


In [19]:
# Create a 5x5 matrix with values 1,2,3,4,7 on the diagonal* using np.diag
diagonal_elements = np.array([1, 2, 3, 4, 7])

diagonal_matrix = np.diag(diagonal_elements)
print(diagonal_matrix)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 7]]


In [20]:
# Create a 8x8 matrix and fill it with a checkerboard pattern using slicing
check_board_array = np.ones((3,3))

check_board = np.zeros((8,8), dtype=int)
check_board[1::2, ::2] = 1
check_board[::2, 1::2] = 1

print(check_board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [21]:
# Given a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? Use np.unravel_index.
index = np.unravel_index(100, (6, 7, 8))
print(index)

(np.int64(1), np.int64(5), np.int64(4))


In [22]:
# Normalize* a 5x5 random matrix. The normalization formula is (matrix - matrix.min()) / (matrix.max() - matrix.min())
matrix = np.random.rand(5, 5)

matrix_min = matrix.min()
matrix_max = matrix.max()

normalized_matrix = (matrix - matrix.min()) / (matrix.max() - matrix.min())

print(normalized_matrix)

[[0.85247119 0.937504   0.14508323 0.89782494 0.32086495]
 [0.15153932 1.         0.05503183 0.33715088 0.79392003]
 [0.92167062 0.65848675 0.03180974 0.65872684 0.9269956 ]
 [0.00247589 0.         0.07025173 0.23887344 0.55767052]
 [0.75851837 0.90234168 0.33539044 0.8102154  0.70397591]]


In [25]:
# Given a two-dimensional array, extract unique rows. You can use np.unique with the axis argument.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [1, 2, 3],
                [7, 8, 9],
                [4, 5, 6]])
print(arr)
print()
unique_rows = np.unique(arr, axis=0)
print(unique_rows)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]
 [4 5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
# Create a structured array* representing a position (x,y) and a color (r,g,b). Use np.dtype to create a custom dtype for this task.

# Define a custom dtype for position (x, y) and color (r, g, b)
position_color_dtype = np.dtype([
    ('position', [('x', 'f4'), ('y', 'f4')]),  # float32 for position
    ('color',    [('r', 'u1'), ('g', 'u1'), ('b', 'u1')])  # uint8 for color (0–255)
])

# Create a structured array with 3 elements as an example
data = np.array([
    ((1.0, 2.0), (255, 0, 0)),
    ((3.5, 4.5), (0, 255, 0)),
    ((5.0, 6.0), (0, 0, 255))
], dtype=position_color_dtype)

# Print the structured array
print(data)

[((1. , 2. ), (255,   0,   0)) ((3.5, 4.5), (  0, 255,   0))
 ((5. , 6. ), (  0,   0, 255))]


In [28]:
# How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? Use np.add.at. This method performs unbuffered* in place operation on operand ‘a’ for elements specified by ‘indices’.

F = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 2, 0, 1])
X = np.array([10, 20, 30, 40, 50])

np.add.at(F, I, X)
print(F)

[51 72 33  4  5]


In [29]:
# Considering a four dimensions array, how to get sum over the last two axis at once? Use np.sum with axis=(-2,-1)

arr_sum = np.arange(120).reshape(2,3,4,5)

array_sum = np.sum(arr_sum, axis=(-2,-1))
print(array_sum)

[[ 190  590  990]
 [1390 1790 2190]]


In [32]:
# How to get the diagonal of a dot product? Use np.diag and np.dot
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

diagonal_of_dot_product = np.diag(np.dot(array1, array2))

print(diagonal_of_dot_product)

[19 50]


In [35]:
# Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?
# This involves use of np.zeros and array indexing.

interval_array = np.array([1, 2, 3, 4, 5])

# Displaying the original array 'nums'
print("Original array:")
print(interval_array)

# Variable 'p' set to 2
p = 2

# Creating a new array 'new_nums' of length len(nums) + (len(nums) - 1) * p filled with zeros
new_nums = np.zeros(len(interval_array) + (len(interval_array) - 1) * (p))

# Filling the 'new_nums' array with elements from 'nums' at intervals of (p + 1)
new_nums[::p + 1] = interval_array

# Displaying the new array 'new_nums'
print("\nNew array:")
print(new_nums)

Original array:
[1 2 3 4 5]

New array:
[1. 0. 0. 2. 0. 0. 3. 0. 0. 4. 0. 0. 5.]


In [36]:
# How to compute averages using a sliding window over an array? 
# This involves some manipulation of array indexing and arithmetic operations. 
# Essentially, you would compute a cumulative sum* and then subtract the sum at 
# the beginning of the window from each element.

def sliding_window_avg(arr, window_size):
    # Compute cumulative sum, padded with a 0 at the start
    cumsum = np.cumsum(np.insert(arr, 0, 0))  # insert 0 to align window starts
    
    # Compute window sums using differences in cumsum
    window_sums = cumsum[window_size:] - cumsum[:-window_size]
    
    # Compute average
    return window_sums / window_size

# Example usage
arr = np.array([1, 2, 3, 4, 5, 6, 7])
window_size = 3
result = sliding_window_avg(arr, window_size)

print("Sliding window averages:", result)

Sliding window averages: [2. 3. 4. 5. 6.]


In [37]:
# Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws 
# from a multinomial distribution* with n degrees, i.e., the rows which only contain integers and which sum to n. 
# This involves understanding of multinomial distribution.

def valid_multinomial_rows(X, n):
    # Condition 1: All elements are integers (no decimal part)
    is_integer = np.all(np.mod(X, 1) == 0, axis=1)
    
    # Condition 2: Each row must sum to n
    has_sum_n = np.sum(X, axis=1) == n
    
    # Both conditions
    valid = np.logical_and(is_integer, has_sum_n)
    
    # Return only valid rows
    return X[valid]

# Example
X = np.array([
    [2, 3, 5],
    [1.5, 2, 6.5],
    [4, 4, 2],
    [3, 3, 3]
])
n = 10

result = valid_multinomial_rows(X, n)
print("Valid multinomial rows:\n", result)

Valid multinomial rows:
 [[2. 3. 5.]
 [4. 4. 2.]]


In [38]:
# Compute bootstrapped 95% confidence intervals* for the mean of a 1D array X (i.e., resample the elements 
# of an array with replacement N times, compute the mean of each sample, 
# and then compute percentiles over the means). Use np.percentile.
def bootstrap_ci_mean(X, N=1000, ci=95):
    means = []
    for _ in range(N):
        # Resample with replacement
        sample = np.random.choice(X, size=len(X), replace=True)
        means.append(np.mean(sample))
    
    # Compute confidence interval percentiles
    lower = np.percentile(means, (100 - ci) / 2)
    upper = np.percentile(means, 100 - (100 - ci) / 2)
    
    return lower, upper

# Example usage
X = np.array([2, 4, 6, 8, 10])
ci_lower, ci_upper = bootstrap_ci_mean(X)

print(f"Bootstrapped 95% CI for mean: ({ci_lower:.2f}, {ci_upper:.2f})")

Bootstrapped 95% CI for mean: (3.60, 8.40)
