In [54]:
# Exercise 1

# 1 Import the numpy package under the name np.
import numpy as np
import random

# 2 Create a vector* of zeros with size 10 using np.zeros().
array_1d = np.zeros(10)
print(array_1d)
# 3 Compute the memory size* of any array. Note: You can do this by multiplying 
# 3 the length of the array by the size of one array element, which you can find using the .itemsize attribute.
print(f"The itemsize is {array_1d.itemsize}")
# 4 Retrieve the documentation of the numpy add function from the command line.
# help(np.add)

# 5 Create a vector with values ranging from 10 to 49 using np.arange().
array_arange = np.arange(10, 50)
print(array_arange)
# 6 Reverse a vector so the first element becomes last (Hint: Use slicing).
print(array_arange[::-1])

# 7 Create a 3x3 matrix* with values ranging from 0 to 8 using np.reshape().
array_matrix = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
new_array_matrix = array_matrix.reshape(3,3)
print(new_array_matrix)

# 8 Find indices of non-zero elements from [1,2,0,0,4,0] using np.nonzero().
non_zero_array = np.array([1,2,0,0,4,0])
nza1 = np.nonzero(non_zero_array)
print(nza1)

# 9 Create a 3x3 identity matrix* using np.eye().
identity_matrix = np.eye(3)
print(identity_matrix)

# 10 Create a 5x5 matrix with row values ranging from 0 to 4. 
# The output should be a matrix where each row is [0, 1, 2, 3, 4].
array_5_matrix = np.zeros((5,5))
array_5_matrix += np.arange(5)
print(array_5_matrix)

# 11 Create a vector of size 10 with values ranging from 0 to 1, both excluded. You can use np.linspace.
array_evenly = np.linspace(0,1,10)
print(array_evenly)

# 12 Create a random vector of size 10 and sort it.
array_random = np.random.random(10)
array_random.sort()
print(array_random)

# 13 Print the minimum and maximum representable value for each numpy scalar type* 
# (int8, int32, int64, float32, float64). Use np.iinfo and np.finfo.
iinfo_int8 = np.iinfo(np.int8)
print(f"Min value int8 {iinfo_int8.min}")
print(f"Min value int8 {iinfo_int8.max}")

iinfo_int32 = np.iinfo(np.int32)
print(f"Min value int32 {iinfo_int32.min}")
print(f"Min value int32 {iinfo_int32.max}")

iinfo_int64 = np.iinfo(np.int64)
print(f"Min value int64 {iinfo_int64.min}")
print(f"Min value int64 {iinfo_int64.max}")

finfo_float32 = np.finfo(np.float32)
print(f"Min value float32 {finfo_float32.min}")
print(f"Min value float32 {finfo_float32.max}")

finfo_float64 = np.finfo(np.float64)
print(f"Min value float32 {finfo_float64.min}")
print(f"Min value float32 {finfo_float64.max}")

# 14 How to convert a float (32 bits) array into an integer (32 bits) in place? Use np.ndarray.astype
int_array = np.array([1, 2, 3, 4, 5])
float_array = int_array.astype(float)
print(f"Converted array float {float_array}")

# 15 Subtract the mean* of each row of a matrix. Use np.mean with axis=1.
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6],
                   [7, 8, 9]])

arr_2d_mean = np.mean(arr_2d, axis=1)
print(arr_2d_mean)

# 16 How to sort an array by the nth column? Use np.argsort.
arr_2d_1 = np.array([10, 5, 30, 20])

indices = np.argsort(arr_2d_1)
print(f"indices", arr_2d_1[indices])

# 17 How to swap two rows of an array? You can do this using array indexing.
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

arr[[0, 1]] = arr[[1, 0]]
print(arr)

# Given an array C that is a bincount*, how to produce an array A such that np.bincount(A) == C? Use np.repeat.
C = np.array([0, 2, 1, 3])

A = np.repeat(np.arange(len(C)), C)

print("Recovered A:", A)
print("Check:", np.bincount(A))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
The itemsize is 8
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(array([0, 1, 4]),)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.1296011  0.25103575 0.42519696 0.45015292 0.45143833 0.65477394
 0.74851489 0.89637021 0.9669602  0.99584803]
Min value int8 -128
Min value int8 127
Min value int32 -2147483648
Min value int32 2147483647
Min value int64 -9223372036854775808
Min value int64 9223372036854775807
Min value float32 -3.4028234663852886e+38
Min value float32 3.4028234663852886e+38
Min value float32 -1.7976931348623157e+308
Min value